FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY apps/backend/package.json apps/backend/package.json

RUN npm install

COPY apps/backend ./apps/backend

EXPOSE 3000

CMD ["npm", "--workspace", "apps/backend", "run", "start:dev"]
